# Generated by Django 5.1.7 on 2025-03-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                ("income", models.FloatField()),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("Urban", "Urban"),
                            ("Rural", "Rural"),
                            ("Suburban", "Suburban"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "ad_type",
                    models.CharField(
                        choices=[
                            ("Banner", "Banner"),
                            ("Video", "Video"),
                            ("Text", "Text"),
                            ("Native", "Native"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ad_topic", models.CharField(max_length=50)),
                (
                    "ad_placement",
                    models.CharField(
                        choices=[
                            ("Social Media", "Social Media"),
                            ("Search Engine", "Search Engine"),
                            ("Website", "Website"),
                        ],
                        max_length=20,
                    ),
                ),
                ("clicks", models.IntegerField()),
                ("click_time", models.DateTimeField()),
                ("conversion_rate", models.FloatField()),
                ("ctr", models.FloatField()),
            ],
        ),
    ]
