# Generated by Django 5.1.7 on 2025-03-24 04:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="impressions",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="click_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
